site_name: Smart Media Documentation
nav:
    - Home: index.md
    - Test: test.md
    - UU: universell-utforming.md
markdown_extensions:
    - toc:
        baselevel: 2
        toc_depth: "1-2"
theme: readthedocs

